[package]
name = "happens"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.1", features = ["derive"] }
copypasta = "0.8.2"
phf = { version = "0.11.1", features = ["macros"] }
xdotool = "0.0.2"
